### ISSUE TITLE
New GEOS 3.10.0 version number breaks sfdct

### ISSUE THREAD

**Issue by rsbivand** [hypertidy/sfdct#15]
Because GEOS will go to 3.10.0 at next release, the version test: `Error in st_triangulate.sfc(st_geometry(x), dTolerance, bOnlyEdges) : for triangulate, GEOS version 3.4.0 or higher is required` fails. See https://github.com/r-spatial/sf/issues/1653 for remedies.  
[00check.log](https://github.com/hypertidy/sfdct/files/6386568/00check.log)

**Comment by mdsumner** [comment]
Thank you, removed the cause of the issue (an example). 

linked PR should suffice when an update is required
